#!/usr/bin/bash

cd "src"

lastday=$(find . -type d -regex '\./day[0-9]+' | grep -o '[0-9]*' | sort -n | tail -1)
newday=$(printf "%02d" $(( 10#${lastday:-0} + 1 )))

cp -r "template" "day$newday"
cd "day$newday"
